
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: dev
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: dHVfcGFzc3dvcmRfc2VndXJv
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: dev
type: Opaque
data:
  RABBITMQ_URL: YW1xcDovL3VzZXI6cGFzc3dvcmRAcmFiYml0bXEtc2VydmljZTo1Njcy
